require('dotenv').config();
const fs=require('fs'),https=require('https'),path=require('path');
const TELEGRAM_TOKEN=process.env.TELEGRAM_TOKEN_TRACK||process.env.TELEGRAM_TOKEN;
const TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID_TRACK||process.env.TELEGRAM_CHAT_ID;
const ANTHROPIC_KEY=process.env.ANTHROPIC_API_KEY;
const IMAP_USER=process.env.IMAP_USER||process.env.ERP_USER;
const IMAP_PASS=process.env.IMAP_PASS||process.env.ERP_PASS;
const POLL_MS=5*60*1000;
const SEEN_FILE=path.join(__dirname,'seen-emails.json');
const LOG_FILE=path.join(__dirname,'daily-log.json');
const QUESTIONS_FILE=path.join(__dirname,'questions-db.json');
const GITHUB_TOKEN=process.env.GITHUB_TOKEN;
const GITHUB_REPO='mikeljungbergtvedt/mikeljungbergtvedt.github.io';
const QUESTIONS_PATH='peasy-questions.json';
